//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTests.ModelTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmsGenres
    {
        public int IdFilmGenre { get; set; }
        public int IdFilm { get; set; }
        public int IdGenre { get; set; }
    
        public virtual Films Films { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
