//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Films
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Films()
        {
            this.FilmsCountries = new HashSet<FilmsCountries>();
            this.FilmsGenres = new HashSet<FilmsGenres>();
            this.Sessions = new HashSet<Sessions>();
        }
    
        public int IdFilm { get; set; }
        public string NameFilm { get; set; }
        public string DescriptionFilm { get; set; }
        public int IdAgeLimit { get; set; }
        public System.TimeSpan Duration { get; set; }
        public string Actors { get; set; }
        public string FilmsCompany { get; set; }
        public string FilmsDirectors { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual AgeLimits AgeLimits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmsCountries> FilmsCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmsGenres> FilmsGenres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sessions> Sessions { get; set; }
    }
}
