//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HallsSeats
    {
        public int IdSeat { get; set; }
        public int IdHall { get; set; }
        public int Row { get; set; }
        public int NumberSeat { get; set; }
    
        public virtual Halls Halls { get; set; }
    }
}
